version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    container_name: neoway-fullstack-mongo
    networks:
      - neoway-fullstack-network
    ports:
      - 27017:27017
    volumes:
      - ./api/data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  api:
    build:
      context: ./api
      target: service
    container_name: neoway-fullstack-api
    ports:
      - 11000:3000
    depends_on:
      - mongo
    env_file:
      - docker-compose.env
    networks:
      - neoway-fullstack-network

  client:
    build:
      context: ./client
    container_name: neoway-fullstack-client
    networks:
      - neoway-fullstack-network
    ports:
      - 8080:8080
    depends_on:
      - api
    env_file:
      - docker-compose.env

  test-api:
    build:
      context: ./api
      target: test
    container_name: neoway-fullstack-test
    networks:
      - neoway-fullstack-network
    depends_on:
      - api
    env_file:
      - docker-compose.env

networks:
  neoway-fullstack-network:
    name: neoway-fullstack-network
    driver: bridge
