version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    container_name: blocklist-challenge-mongo
    networks:
      - blocklist-challenge-network
    ports:
      - 27017:27017
    volumes:
      - ./api/data/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  api:
    build:
      context: ./api
      target: service
    container_name: blocklist-challenge-api
    restart: always
    ports:
      - 11000:11000
    depends_on:
      - mongo
    networks:
      - blocklist-challenge-network
    env_file:
      - docker-compose.env

  client:
    build:
      context: ./client
      target: application
    container_name: blocklist-challenge-client
    restart: always
    networks:
      - blocklist-challenge-network
    ports:
      - 5173:5173
    depends_on:
      - api
    env_file:
      - docker-compose.env
    volumes:
      - ./client:/app

  test-api:
    build:
      context: ./api
      target: test
    container_name: blocklist-challenge-test-api
    networks:
      - blocklist-challenge-network
    depends_on:
      - api
    env_file:
      - docker-compose.env

  test-client:
    build:
      context: ./client
      target: test
    container_name: blocklist-challenge-test-client
    networks:
      - blocklist-challenge-network
    depends_on:
      - client
    env_file:
      - docker-compose.env

networks:
  blocklist-challenge-network:
    name: blocklist-challenge-network
    driver: bridge
